&_hook_kernel32__CreateProcessA,
    &_hook_kernel32__CreateProcessW,
    &_hook_kernel32__LoadLibraryA,
    &_hook_kernel32__LoadLibraryExA,
    &_hook_kernel32__LoadLibraryExW,
    &_hook_kernel32__LoadLibraryW,
    &_hook_kernel32__LoadModule,
    &_hook_kernel32__GetProcAddress,
